/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.LecturerDAO;
import utils.TableStyler;
import dao.LecturerDAOImpl;
import model.Lecturer;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import utils.Session;

public class LecturerDialog extends javax.swing.JDialog {

    private LecturerDAO lecturerDAO;
    
    public LecturerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lecturerDAO = new LecturerDAOImpl();
        loadLecturers();

        setLocationRelativeTo(null);
    }
    
    private void loadLecturers() {
        int userId = Session.getUser().getId();

        List<Lecturer> list = lecturerDAO.getAll(userId);
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"ID", "Nama Dosen"}, 0
        );

        for (Lecturer l : list) {
            model.addRow(new Object[]{l.getId(), l.getName()});
        }

        tbLecturer.setModel(model);
        TableStyler.styleTable(tbLecturer);
        hideIdColumn(tbLecturer);
    }


    private void hideIdColumn(JTable table) {
        table.getColumnModel().getColumn(0).setMinWidth(0);
        table.getColumnModel().getColumn(0).setMaxWidth(0);
        table.getColumnModel().getColumn(0).setWidth(0);
        table.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        scrolltableLecturer = new javax.swing.JScrollPane();
        tbLecturer = new javax.swing.JTable();
        panelToolbar = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Kelola Dosen");

        scrolltableLecturer.setBackground(new java.awt.Color(255, 255, 255));

        tbLecturer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbLecturer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrolltableLecturer.setViewportView(tbLecturer);

        panelToolbar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelToolbarLayout = new javax.swing.GroupLayout(panelToolbar);
        panelToolbar.setLayout(panelToolbarLayout);
        panelToolbarLayout.setHorizontalGroup(
            panelToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelToolbarLayout.setVerticalGroup(
            panelToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrolltableLecturer, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrolltableLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String name = JOptionPane.showInputDialog(this, "Nama Dosen:");
        if (name != null && !name.trim().isEmpty()) {
            int userId = Session.getUser().getId();
            Lecturer l = new Lecturer(0, userId, name.trim());
            if (lecturerDAO.add(l)) {
                JOptionPane.showMessageDialog(this, "Berhasil menambahkan!");
                loadLecturers();
                if (getParent() instanceof MainFrame) {
                    ((MainFrame) getParent()).refreshLecturerCombo();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambahkan.");
            }
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int row = tbLecturer.getSelectedRow();
        if (row != -1) {
            int id = (int) tbLecturer.getValueAt(row, 0);
            String currentName = (String) tbLecturer.getValueAt(row, 1);
            String newName = JOptionPane.showInputDialog(this, "Edit Nama Dosen:", currentName);
            if (newName != null && !newName.trim().isEmpty()) {
                int userId = Session.getUser().getId();
                Lecturer l = new Lecturer(id, userId, newName.trim());
                if (lecturerDAO.update(l)) {
                    JOptionPane.showMessageDialog(this, "Berhasil diperbarui!");
                    loadLecturers();
                    if (getParent() instanceof MainFrame) {
                        ((MainFrame) getParent()).refreshLecturerCombo();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal diperbarui.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris dulu!");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int row = tbLecturer.getSelectedRow();
        if (row != -1) {
            int id = (int) tbLecturer.getValueAt(row, 0);
            int confirm = JOptionPane.showConfirmDialog(this, "Yakin mau hapus?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                int userId = Session.getUser().getId();
                if (lecturerDAO.delete(id, userId)) {
                    JOptionPane.showMessageDialog(this, "Berhasil dihapus!");
                    loadLecturers();
                    if (getParent() instanceof MainFrame) {
                        ((MainFrame) getParent()).refreshLecturerCombo();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal dihapus.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris dulu!");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelToolbar;
    private javax.swing.JScrollPane scrolltableLecturer;
    private javax.swing.JTable tbLecturer;
    // End of variables declaration//GEN-END:variables
}
